# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Cup of Python
email: pavel12py@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Cup of Python is a personal blog about little Python projects and Sysadmin
  daily tasks on GNU/Linux & UNIX. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pavelinux.github.io" # the base hostname & protocol for your site
twitter_username: pavel12py
github_username:  pavelinux

# Build settings
markdown: kramdown
# Google Analytics
ga_tracking_id: UA-76985972-1
# Disqus
disqus_domain: acupofpython.disqus.com
